### ISSUE TITLE
请问如何将一个64位的整数反序列化

### ISSUE THREAD

**Issue by StarryPortrait** [Ryan-CW-Code/RyanDocs#1]

**Comment by StarryPortrait** [comment]
还有一个问题
```
void ryanjson_test2()
{
    RyanJson_t jsonRoot = RyanJsonCreateObject();

    RyanJsonAddDoubleToObject(jsonRoot, "double", 16.89);
    char *str = RyanJsonPrint(jsonRoot, 250, RyanJsonFalse, NULL);
    printf("%s\n", str);

    RyanJsonFree(str);
    RyanJsonDelete(jsonRoot);
}
```
当我使用如上，反序列化double时，输出结果为 **{"double":}**

**Comment by Ryan-CW-Code** [comment]
![image](https://github.com/user-attachments/assets/3d1018c8-7004-43fc-b956-c895d63c3154)
没有复现您说的情况，需要您提供更多的信息。

**Comment by Ryan-CW-Code** [comment]
RyanJson目前不支持64位整数，它现在使用int/double类型表示`number`，最高精度为double类型的63位，以后可能会引入64位数支持(会占用更多的内存)。
目前建议您将64位整数转为字符串使用。

**Comment by Ryan-CW-Code** [comment]
此issue可以移步到[RyanJson](https://github.com/Ryan-CW-Code/RyanJson)仓库中讨论。
